# Generated by Django 4.2.2 on 2023-06-20 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paladweb', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprador',
            name='department',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='comprador',
        ),
    ]
