# Generated by Django 4.2.2 on 2023-06-20 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paladweb', '0004_remove_comprador_department_remove_venta_comprador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='author',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='TIENDA',
        ),
    ]
