# Generated by Django 4.2.2 on 2023-06-21 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paladweb', '0006_evento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='venta',
            new_name='cita',
        ),
        migrations.RemoveField(
            model_name='comprador',
            name='user',
        ),
        migrations.DeleteModel(
            name='evento',
        ),
        migrations.DeleteModel(
            name='producto',
        ),
        migrations.DeleteModel(
            name='comprador',
        ),
    ]
